### ISSUE TITLE
Transfer old Tixati configs (torrents) to this docker

### ISSUE THREAD

**Issue by pecuna** [kyzima-spb/docker-tixati#4]
Hi!
I just found your docker and want to give it a try.
But I have a 500+ torrents in my Tixati installation (portable)
How can I transfer them correctly with all of their options set?
I tried to mount a volume (directory with the settings) to /home/user/.tixati 
But that broke it :D
And with VNC I can see a message "Waiting for other instance of Tixati to save and exit..." and only "Cancel" as a button

I mounted my downlods directory to the same directory as on other servers. I verified it in the docker.
Could you please provide some guidelines for migration?

**Comment by kyzima-spb** [comment]
Good day.

Super! I have not encountered such a problem, but I wanted to advise the import and export of settings.

The mount point inside the container can be any, the main thing is that the access rights match the host machine.

Thanks for the kind words =)

**Comment by pecuna** [comment]
Just to let you know that after the importation you could cp the settings from /home/user/.tixati to the downloads dir, and after that use this directory with volume mount and you have the settings restored with a new container, without manually importing anything.
